########################
# FYSIO NETLIFY CONFIG #
########################

[build]
command = "nuxt build"
publish = "dist"

[dev]
command = "yarn dev" # Command to start your dev server
#    publish = "dist" # The path to your static content folder
autoLaunch = false # a Boolean value that determines if Netlify Dev launches the local server address in your browser
